### PR TITLE
Add parse type to threads and post.

### PR DESCRIPTION
**Pull request by JeldorPKU**
RT.
Also fixed the class name of `Threads` which should be `Thread`.

### CODE REVIEW

**Comment by JeldorPKU** [comment]
@huxuan  @zhzhzoo Have a look.

**Comment by huxuan** [comment]
Actually, I suppose the `thread` should only have the subject/title information, all contents should belongs to `post` including the first floor. In that way, we only need `type` for `post` rather than for both. And `type` should be clear enough, you seems to be too explicit. I don't think our system will be that much complicated.

**Comment by zhzhzoo** [comment]
哦我也觉得应该只是 `post` 有～

**Comment by JeldorPKU** [comment]
I have improved the code according to your suggestions. However, `type` is a built-in function in Python 2. Does it matter to use this word as a variable name? @huxuan

**Comment by huxuan** [comment]
> type is a built-in function in Python 2. Does it matter to use this word as a variable name?

OK, you are right. Sorry for my carelessness. Let's just keep using `parse_type` or think up a new proper alternative variable name. BTW, we do can use `type` as an variable, but it's not a good habit.

**Comment by JeldorPKU** [comment]
OK, I will update it tomorrow when I get home.

**Pull request merged**
